[project]
authors = ["Cade Mirchandani <cmirchan@ucsc.edu>"]
channels = ["conda-forge", "bioconda"]
name = "symbiont_transmission"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
pip = ">=25.0.1,<26"
snakemake = ">=9.1.2, <10"
numpy = ">=2.2.4, <3"
matplotlib = ">=3.10.1, <4"
pandas = ">=2.2.3, <3"
seaborn = ">=0.13.2, <0.14"
scipy = ">=1.16.2, <2"
scikit-learn = ">=1.7.2, <2"
ipykernel = ">=7.2.0,<8"

[pypi-dependencies]
snkmt = ">=0.2.4, <0.3"
